### ISSUE TITLE
`Create Check` missing required properties in `scripts/generated/endpoints.json`

### ISSUE THREAD

**Issue by oscard0m** [octokit/plugin-rest-endpoint-methods.js#441]
**What happened?**
Expected _required_ properties in documentation for `create check run` are missing:
* `name`
* `head_sha`

Instead a strange `*` property appears (`scripts/update-endpoints/generated/endpoints.json` Line 9888):

<details>
  <summary>Click to expand!</summary>
  
  ```json
    "parameters": [
      {
        "name": "owner",
        "description": "",
        "in": "PATH",
        "type": "string",
        "required": true,
        "enum": null,
        "allowNull": false,
        "mapToData": null,
        "validation": null,
        "alias": null,
        "deprecated": null
      },
      {
        "name": "repo",
        "description": "",
        "in": "PATH",
        "type": "string",
        "required": true,
        "enum": null,
        "allowNull": false,
        "mapToData": null,
        "validation": null,
        "alias": null,
        "deprecated": null
      },
      {
        "name": "status",
        "description": "",
        "in": "BODY",
        "type": null,
        "required": false,
        "enum": ["queued", "in_progress"],
        "allowNull": false,
        "mapToData": null,
        "validation": null,
        "alias": null,
        "deprecated": null
      },
      {
        "name": "*",
        "description": "",
        "in": "BODY",
        "type": "object",
        "required": false,
        "enum": null,
        "allowNull": false,
        "mapToData": null,
        "validation": null,
        "alias": null,
        "deprecated": null
      }
    ]
  ```
</details>

**What did you expect to happen?**
To get missing `name` and `head_sha` required properties when running `npm run update-endpoints:fetch-json`

**What the problem might be**
`github-openapi-graphql-query` lib is returning wrong info probably. Opened issue in that project: https://github.com/gr2m/github-openapi-graphql-query/issues/11

**Comment by gr2m** [comment]
I tried to reproduce the problems with `@octokit/types`, but no luck:
[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYBNLFTAznAXzgDMoIQ4AiAAQgGMYIBrYGAehgE8wBTXSgFAC6EVLngA3AIYAbYOgBcKDFhy4A2pQAKAeQDKAFThsoPSLjYIIAd1Q8oBS6ciO6ACx50mAWigBXMUoAXU0wKSgpEB4Ye34guABeRAE4VLgbOyglSkoAGhS05whsvILU1EieEvy0uA8pdAB9XDcpEoECIRExeGxpOUVlTAhsPE1dQ2Miiytbe0cEItcPL18AuNDwypioOMTk2oz7arK4IvaCIA)

<img width="700" alt="image" src="https://user-images.githubusercontent.com/39992/133168260-1b10feea-411a-44b6-bf21-7ced38cd2563.png">

However when using the REST API endpoint method `.checks.create()` no parameters seem to be required at all, or suggested by the TS IntelliSense

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAeigFMBnGMgKHdQgDtW5qGbPAC8cHowDuKGsIAUASk6DaMAHRNIzNQHNGMOQnZwTAyRKgAucmQA0x05ojWyHXEvYrha1AAtGqJjaqEwAhjCMhg4mEOaMVjb2pnBOLnbRcHR04qEgjGlJpllw-qEAJgD6zL6haezuQA)

<img width="597" alt="image" src="https://user-images.githubusercontent.com/39992/133168542-e19a2da8-7d68-498d-b595-d667a1345b95.png">

The problem seems indeed to be with `@octokit/plugin-rest-endpoint-methods` [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgJQKYGcYFEB2ATSYHGAWVRgAsI8AVATzAzgF84AzKCEOAIgAEIAYxgQA1sBgB6MABsArgHMiAWigYYy1PkLFlIclTzoeAKBOCIOTHBjqAXCnW4CEIqQPV6jdAG0egilRBUWMAXT9BNQBDWx5wnjAoqCj9WygwuABeRBM4PLgTZiA)

<img width="634" alt="image" src="https://user-images.githubusercontent.com/39992/133168680-7c3b80d6-8dd7-4b26-9a64-2cbed6000bbc.png">

I guess you got that far yourself :) I'll have a look why that is and if it's related to the problem you reported at https://github.com/gr2m/github-openapi-graphql-query/issues/11

**Comment by gr2m** [comment]
It looks like a problem with `Omit` and `Endpoints["POST /repos/{owner}/{repo}/check-runs"]["parameters"]`: 
[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYBNLFTAznAXzgDMoIQ4AiAAQgGMYIBrYGAehgE8wBTXSgNwAoIV15wAKn3gBeOAHkQrADxC4KDFhy4A2pQAK8gMoS4bKD0i42CCAHdUPKARsXILugAsedJgFooAFdUfgBdPTAAQyhIkB4YJzCAGjUqACNI3B4AVSgAG0o4AB8qb0j0RMKSyjj0YEiJbh5KIQA+YVEmyWkAJjg5NEwIbDw9QxMzNwhrWwcnFwQpj29fAOCwiOjY+MrQjroIEPgE3BgALm7TvrkEAmEgA)

<img width="749" alt="image" src="https://user-images.githubusercontent.com/39992/133169649-4c00e298-853f-47a5-a472-e195ac97eef8.png">

Any idea what it could be? I have to move on for today but will try to look more into it on Wednesday

**Comment by oscard0m** [comment]
> It looks like a problem with `Omit` and `Endpoints["POST /repos/{owner}/{repo}/check-runs"]["parameters"]`:
> [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYBNLFTAznAXzgDMoIQ4AiAAQgGMYIBrYGAehgE8wBTXSgNwAoIV15wAKn3gBeOAHkQrADxC4KDFhy4A2pQAK8gMoS4bKD0i42CCAHdUPKARsXILugAsedJgFooAFdUfgBdPTAAQyhIkB4YJzCAGjUqACNI3B4AVSgAG0o4AB8qb0j0RMKSyjj0YEiJbh5KIQA+YVEmyWkAJjg5NEwIbDw9QxMzNwhrWwcnFwQpj29fAOCwiOjY+MrQjroIEPgE3BgALm7TvrkEAmEgA)
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/39992/133169649-4c00e298-853f-47a5-a472-e195ac97eef8.png">
> 
> Any idea what it could be? I have to move on for today but will try to look more into it on Wednesday

Buf, no idea. I guess we are doing something crazy with this chain of types and an `Omit` is not able to infer the "omission". I will try to take a look this week too. Thanks for taking the time on checking this and arriving that far :)

**Comment by wolfy1339** [comment]
Is there any update to this issue, or is it no longer a problem?
