### ISSUE TITLE
How to update some of the endpoints

### ISSUE THREAD

**Issue by igalarzab** [octokit/plugin-rest-endpoint-methods.js#469]
Hi!

I've trying to figure out by reading the `CONTRIBUTING.md` file and few of the merged PRs how this repository updates the endpoints but I'm still not very sure if there is an automated process... and also what's the process to release new versions of the library

There are few endpoints that I see are outdated given what the official GH docs say. Few examples are:

1) https://docs.github.com/en/rest/reference/repos#get-repository-permissions-for-a-user
This endpoint has a new field (`role_name`), that's not exposed by this lib

2) https://docs.github.com/en/rest/reference/repos#update-branch-protection
This endpoint accepts a new attribute (`required_status_checks.checks`) that's not supported here

What would be the process to update these two calls?

**Comment by wolfy1339** [comment]
There is currently no active maintainer for the JS octokit packages.

You can check out [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174) for updates.

Endpoint updates are an automated process that have been disabled due to the previous point.

Alternatively, you can use `octokit.request()` to call an endpoint directly if it's missing/differing from the current version published.
