### ISSUE TITLE
octokit.repos.deleteDeployment doesn't exist

### ISSUE THREAD

**Issue by ssboisen** [octokit/plugin-rest-endpoint-methods.js#60]
**What happened?**

Trying to use octokit.repos.deleteDeployment but function doesn't exist thus resulting in exception being thrown.

**What did you expect to happen?**

Expected it to be there since it's part of the documentation

**What the problem might be**

I don't know but I can say as much that using `octokit.request('DELETE /repos/:owner/:repo/deployments/:deployment_id',{})` works.

**Comment by gr2m** [comment]
I tried to reproduce your bug, but had no luck:
https://runkit.com/gr2m/octokit-plugin-rest-endpoint-methods-js-60/1.0.0

What version of `@octokit/plugin-rest-endpoint-methods` do you use? Run `npm ls @octokit/plugin-rest-endpoint-methods` to find out

**Comment by ssboisen** [comment]
I should have mentioned this in my original report, i'm using @actions/github

https://runkit.com/ssboisen/octokit-plugin-rest-endpoint-methods-js-60

**Comment by ssboisen** [comment]
@gr2m Sorry I just realized what the problem is. `@actions/github` uses and older version of `@octokit/rest` which still depend on v2.4.0 of `@octokit/plugin-rest-endpoint-methods`

**Comment by gr2m** [comment]
I cannot help with `@actions/github` I'm afraid. I asked the maintainers to deprecate this package because people keep running into problems with it :( https://github.com/actions/toolkit/issues/334

Can you use [`@octokit/action`](https://github.com/octokit/action.js) instead? This package is always up-to-date through automated updates, and I maintain it as part of the Octokit suite.

```js
const { Octokit } = require("@octokit/action");
const octokit = new Octokit()

console.log("listDeployments", octokit.repos.listDeployments)
console.log("deleteDeployment", octokit.repos.deleteDeployment)
```

You have to set `GITHUB_TOKEN` via `env:` or `with:` in your workflow YML file

e.g.

```yaml
      - run: node .github/actions/my-script.js
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by gr2m** [comment]
there is nothing actionable for us as it's a problem with `@actions/github`
